//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.25 at 12:19:24 PM EST 
//


package mspsclientcode;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ACNServiceResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACNServiceResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="StatusMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SummaryTaskGuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SummaryTaskName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WorkPlanGuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WorkPlanName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WorkPlanUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACNServiceResponse", namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", propOrder = {
    "statusCode",
    "statusMessage",
    "summaryTaskGuid",
    "summaryTaskName",
    "workPlanGuid",
    "workPlanName",
    "workPlanUrl"
})
public class ACNServiceResponse {

    @XmlElement(name = "StatusCode")
    @XmlSchemaType(name = "unsignedByte")
    protected Short statusCode;
    @XmlElementRef(name = "StatusMessage", namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", type = JAXBElement.class, required = false)
    protected JAXBElement<String> statusMessage;
    @XmlElementRef(name = "SummaryTaskGuid", namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", type = JAXBElement.class, required = false)
    protected JAXBElement<String> summaryTaskGuid;
    @XmlElementRef(name = "SummaryTaskName", namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", type = JAXBElement.class, required = false)
    protected JAXBElement<String> summaryTaskName;
    @XmlElementRef(name = "WorkPlanGuid", namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workPlanGuid;
    @XmlElementRef(name = "WorkPlanName", namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workPlanName;
    @XmlElementRef(name = "WorkPlanUrl", namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workPlanUrl;

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setStatusCode(Short value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStatusMessage(JAXBElement<String> value) {
        this.statusMessage = value;
    }

    /**
     * Gets the value of the summaryTaskGuid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSummaryTaskGuid() {
        return summaryTaskGuid;
    }

    /**
     * Sets the value of the summaryTaskGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSummaryTaskGuid(JAXBElement<String> value) {
        this.summaryTaskGuid = value;
    }

    /**
     * Gets the value of the summaryTaskName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSummaryTaskName() {
        return summaryTaskName;
    }

    /**
     * Sets the value of the summaryTaskName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSummaryTaskName(JAXBElement<String> value) {
        this.summaryTaskName = value;
    }

    /**
     * Gets the value of the workPlanGuid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkPlanGuid() {
        return workPlanGuid;
    }

    /**
     * Sets the value of the workPlanGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkPlanGuid(JAXBElement<String> value) {
        this.workPlanGuid = value;
    }

    /**
     * Gets the value of the workPlanName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkPlanName() {
        return workPlanName;
    }

    /**
     * Sets the value of the workPlanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkPlanName(JAXBElement<String> value) {
        this.workPlanName = value;
    }

    /**
     * Gets the value of the workPlanUrl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkPlanUrl() {
        return workPlanUrl;
    }

    /**
     * Sets the value of the workPlanUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkPlanUrl(JAXBElement<String> value) {
        this.workPlanUrl = value;
    }

}
