//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.25 at 12:19:24 PM EST 
//


package mspsclientcode;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mspsclientcode package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UnsignedLong_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedLong");
    private final static QName _UnsignedByte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedByte");
    private final static QName _UnsignedInt_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedInt");
    private final static QName _Char_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "char");
    private final static QName _Short_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "short");
    private final static QName _Guid_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "guid");
    private final static QName _UnsignedShort_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedShort");
    private final static QName _ACNServiceResponse_QNAME = new QName("http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", "ACNServiceResponse");
    private final static QName _Decimal_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "decimal");
    private final static QName _Boolean_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "boolean");
    private final static QName _Duration_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "duration");
    private final static QName _Base64Binary_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "base64Binary");
    private final static QName _Int_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "int");
    private final static QName _Long_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "long");
    private final static QName _AnyURI_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyURI");
    private final static QName _Float_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "float");
    private final static QName _DateTime_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "dateTime");
    private final static QName _Byte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "byte");
    private final static QName _Double_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "double");
    private final static QName _QName_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "QName");
    private final static QName _AnyType_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyType");
    private final static QName _String_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "string");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestURL_QNAME = new QName("http://tempuri.org/", "rtcWorkRequestURL");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateBusinessArea_QNAME = new QName("http://tempuri.org/", "businessArea");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestID_QNAME = new QName("http://tempuri.org/", "rtcWorkRequestID");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateApplicationName_QNAME = new QName("http://tempuri.org/", "applicationName");
    
    private final static QName _ACNAddTasksToWorkPlanWithWRStatePSInstanceURL_QNAME = new QName("http://tempuri.org/", "PSInstanceURL");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateWorkPlanName_QNAME = new QName("http://tempuri.org/", "workPlanName");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateSummary_QNAME = new QName("http://tempuri.org/", "summary");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateProjectManager_QNAME = new QName("http://tempuri.org/", "projectManager");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateEstimatedStartDate_QNAME = new QName("http://tempuri.org/", "estimatedStartDate");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateEstimatedFinishDate_QNAME = new QName("http://tempuri.org/", "estimatedFinishDate");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateClientName_QNAME = new QName("http://tempuri.org/", "clientName");
    private final static QName _ACNAddTasksToWorkPlanWithWRStatePriority_QNAME = new QName("http://tempuri.org/", "priority");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestRelease_QNAME = new QName("http://tempuri.org/", "rtcWorkRequestRelease");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateAssignedTo_QNAME = new QName("http://tempuri.org/", "assignedTo");
    private final static QName _ACNCreateWorkPlanFromTemplateWithWRStateTemplateName_QNAME = new QName("http://tempuri.org/", "templateName");
    private final static QName _ACNCreateWorkPlanFromTemplateWithWRStatePsInstanceURL_QNAME = new QName("http://tempuri.org/", "psInstanceURL");
    private final static QName _ACNAddTasksToWorkPlanResponseACNAddTasksToWorkPlanResult_QNAME = new QName("http://tempuri.org/", "ACNAddTasksToWorkPlanResult");
    private final static QName _ACNServiceResponseWorkPlanName_QNAME = new QName("http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", "WorkPlanName");
    private final static QName _ACNServiceResponseStatusMessage_QNAME = new QName("http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", "StatusMessage");
    private final static QName _ACNServiceResponseWorkPlanGuid_QNAME = new QName("http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", "WorkPlanGuid");
    private final static QName _ACNServiceResponseSummaryTaskGuid_QNAME = new QName("http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", "SummaryTaskGuid");
    private final static QName _ACNServiceResponseSummaryTaskName_QNAME = new QName("http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", "SummaryTaskName");
    private final static QName _ACNServiceResponseWorkPlanUrl_QNAME = new QName("http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", "WorkPlanUrl");
    private final static QName _ACNCreateWorkPlanFromTemplateWithWRStateResponseACNCreateWorkPlanFromTemplateWithWRStateResult_QNAME = new QName("http://tempuri.org/", "ACNCreateWorkPlanFromTemplateWithWRStateResult");
    private final static QName _ACNAddTasksToWorkPlanWithWRStateResponseACNAddTasksToWorkPlanWithWRStateResult_QNAME = new QName("http://tempuri.org/", "ACNAddTasksToWorkPlanWithWRStateResult");
    private final static QName _ACNAddWBSToWorkPlanRequestID_QNAME = new QName("http://tempuri.org/", "requestID");
    private final static QName _ACNAddWBSToWorkPlanRequestURL_QNAME = new QName("http://tempuri.org/", "requestURL");
    private final static QName _ACNAddWBSToWorkPlanRequestRelease_QNAME = new QName("http://tempuri.org/", "requestRelease");
    private final static QName _ACNCreateWorkPlanFromTemplateResponseACNCreateWorkPlanFromTemplateResult_QNAME = new QName("http://tempuri.org/", "ACNCreateWorkPlanFromTemplateResult");
    private final static QName _ACNAddWBSToWorkPlanResponseACNAddWBSToWorkPlanResult_QNAME = new QName("http://tempuri.org/", "ACNAddWBSToWorkPlanResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mspsclientcode
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ACNAddTasksToWorkPlanResponse }
     * 
     */
    public ACNAddTasksToWorkPlanResponse createACNAddTasksToWorkPlanResponse() {
        return new ACNAddTasksToWorkPlanResponse();
    }

    /**
     * Create an instance of {@link ACNServiceResponse }
     * 
     */
    public ACNServiceResponse createACNServiceResponse() {
        return new ACNServiceResponse();
    }

    /**
     * Create an instance of {@link ACNAddTasksToWorkPlan }
     * 
     */
    public ACNAddTasksToWorkPlan createACNAddTasksToWorkPlan() {
        return new ACNAddTasksToWorkPlan();
    }

    /**
     * Create an instance of {@link ACNCreateWorkPlanFromTemplateWithWRStateResponse }
     * 
     */
    public ACNCreateWorkPlanFromTemplateWithWRStateResponse createACNCreateWorkPlanFromTemplateWithWRStateResponse() {
        return new ACNCreateWorkPlanFromTemplateWithWRStateResponse();
    }

    /**
     * Create an instance of {@link ACNAddTasksToWorkPlanWithWRState }
     * 
     */
    public ACNAddTasksToWorkPlanWithWRState createACNAddTasksToWorkPlanWithWRState() {
        return new ACNAddTasksToWorkPlanWithWRState();
    }

    /**
     * Create an instance of {@link ACNAddTasksToWorkPlanWithWRStateResponse }
     * 
     */
    public ACNAddTasksToWorkPlanWithWRStateResponse createACNAddTasksToWorkPlanWithWRStateResponse() {
        return new ACNAddTasksToWorkPlanWithWRStateResponse();
    }

    /**
     * Create an instance of {@link ACNCreateWorkPlanFromTemplateResponse }
     * 
     */
    public ACNCreateWorkPlanFromTemplateResponse createACNCreateWorkPlanFromTemplateResponse() {
        return new ACNCreateWorkPlanFromTemplateResponse();
    }

    /**
     * Create an instance of {@link ACNAddWBSToWorkPlan }
     * 
     */
    public ACNAddWBSToWorkPlan createACNAddWBSToWorkPlan() {
        return new ACNAddWBSToWorkPlan();
    }

    /**
     * Create an instance of {@link ACNAddWBSToWorkPlanResponse }
     * 
     */
    public ACNAddWBSToWorkPlanResponse createACNAddWBSToWorkPlanResponse() {
        return new ACNAddWBSToWorkPlanResponse();
    }

    /**
     * Create an instance of {@link ACNCreateWorkPlanFromTemplate }
     * 
     */
    public ACNCreateWorkPlanFromTemplate createACNCreateWorkPlanFromTemplate() {
        return new ACNCreateWorkPlanFromTemplate();
    }

    /**
     * Create an instance of {@link ACNCreateWorkPlanFromTemplateWithWRState }
     * 
     */
    public ACNCreateWorkPlanFromTemplateWithWRState createACNCreateWorkPlanFromTemplateWithWRState() {
        return new ACNCreateWorkPlanFromTemplateWithWRState();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedLong")
    public JAXBElement<BigInteger> createUnsignedLong(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnsignedLong_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedByte")
    public JAXBElement<Short> createUnsignedByte(Short value) {
        return new JAXBElement<Short>(_UnsignedByte_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedInt")
    public JAXBElement<Long> createUnsignedInt(Long value) {
        return new JAXBElement<Long>(_UnsignedInt_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "char")
    public JAXBElement<Integer> createChar(Integer value) {
        return new JAXBElement<Integer>(_Char_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "short")
    public JAXBElement<Short> createShort(Short value) {
        return new JAXBElement<Short>(_Short_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedShort")
    public JAXBElement<Integer> createUnsignedShort(Integer value) {
        return new JAXBElement<Integer>(_UnsignedShort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACNServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", name = "ACNServiceResponse")
    public JAXBElement<ACNServiceResponse> createACNServiceResponse(ACNServiceResponse value) {
        return new JAXBElement<ACNServiceResponse>(_ACNServiceResponse_QNAME, ACNServiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "decimal")
    public JAXBElement<BigDecimal> createDecimal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Decimal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "boolean")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "base64Binary")
    public JAXBElement<byte[]> createBase64Binary(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "int")
    public JAXBElement<Integer> createInt(Integer value) {
        return new JAXBElement<Integer>(_Int_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "long")
    public JAXBElement<Long> createLong(Long value) {
        return new JAXBElement<Long>(_Long_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyURI")
    public JAXBElement<String> createAnyURI(String value) {
        return new JAXBElement<String>(_AnyURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "float")
    public JAXBElement<Float> createFloat(Float value) {
        return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "dateTime")
    public JAXBElement<XMLGregorianCalendar> createDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "byte")
    public JAXBElement<Byte> createByte(Byte value) {
        return new JAXBElement<Byte>(_Byte_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "double")
    public JAXBElement<Double> createDouble(Double value) {
        return new JAXBElement<Double>(_Double_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "QName")
    public JAXBElement<QName> createQName(QName value) {
        return new JAXBElement<QName>(_QName_QNAME, QName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyType")
    public JAXBElement<Object> createAnyType(Object value) {
        return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rtcWorkRequestURL", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateRtcWorkRequestURL(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestURL_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "businessArea", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateBusinessArea(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateBusinessArea_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rtcWorkRequestID", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateRtcWorkRequestID(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestID_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "applicationName", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateApplicationName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateApplicationName_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "PSInstanceURL", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStatePSInstanceURL(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStatePSInstanceURL_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "workPlanName", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateWorkPlanName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateWorkPlanName_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "summary", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateSummary(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateSummary_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "projectManager", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateProjectManager(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateProjectManager_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "estimatedStartDate", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateEstimatedStartDate(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateEstimatedStartDate_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "estimatedFinishDate", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateEstimatedFinishDate(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateEstimatedFinishDate_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "clientName", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateClientName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateClientName_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rtcWorkRequestRelease", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateRtcWorkRequestRelease(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestRelease_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "assignedTo", scope = ACNAddTasksToWorkPlanWithWRState.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWithWRStateAssignedTo(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateAssignedTo_QNAME, String.class, ACNAddTasksToWorkPlanWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rtcWorkRequestURL", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateRtcWorkRequestURL(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestURL_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "businessArea", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateBusinessArea(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateBusinessArea_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "summary", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateSummary(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateSummary_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "projectManager", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateProjectManager(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateProjectManager_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "estimatedStartDate", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateEstimatedStartDate(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateEstimatedStartDate_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "estimatedFinishDate", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateEstimatedFinishDate(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateEstimatedFinishDate_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "templateName", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateTemplateName(String value) {
        return new JAXBElement<String>(_ACNCreateWorkPlanFromTemplateWithWRStateTemplateName_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "clientName", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateClientName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateClientName_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rtcWorkRequestID", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateRtcWorkRequestID(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestID_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rtcWorkRequestRelease", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateRtcWorkRequestRelease(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestRelease_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "psInstanceURL", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStatePsInstanceURL(String value) {
        return new JAXBElement<String>(_ACNCreateWorkPlanFromTemplateWithWRStatePsInstanceURL_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "applicationName", scope = ACNCreateWorkPlanFromTemplateWithWRState.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateWithWRStateApplicationName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateApplicationName_QNAME, String.class, ACNCreateWorkPlanFromTemplateWithWRState.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACNServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ACNAddTasksToWorkPlanResult", scope = ACNAddTasksToWorkPlanResponse.class)
    public JAXBElement<ACNServiceResponse> createACNAddTasksToWorkPlanResponseACNAddTasksToWorkPlanResult(ACNServiceResponse value) {
        return new JAXBElement<ACNServiceResponse>(_ACNAddTasksToWorkPlanResponseACNAddTasksToWorkPlanResult_QNAME, ACNServiceResponse.class, ACNAddTasksToWorkPlanResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", name = "WorkPlanName", scope = ACNServiceResponse.class)
    public JAXBElement<String> createACNServiceResponseWorkPlanName(String value) {
        return new JAXBElement<String>(_ACNServiceResponseWorkPlanName_QNAME, String.class, ACNServiceResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", name = "StatusMessage", scope = ACNServiceResponse.class)
    public JAXBElement<String> createACNServiceResponseStatusMessage(String value) {
        return new JAXBElement<String>(_ACNServiceResponseStatusMessage_QNAME, String.class, ACNServiceResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", name = "WorkPlanGuid", scope = ACNServiceResponse.class)
    public JAXBElement<String> createACNServiceResponseWorkPlanGuid(String value) {
        return new JAXBElement<String>(_ACNServiceResponseWorkPlanGuid_QNAME, String.class, ACNServiceResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", name = "SummaryTaskGuid", scope = ACNServiceResponse.class)
    public JAXBElement<String> createACNServiceResponseSummaryTaskGuid(String value) {
        return new JAXBElement<String>(_ACNServiceResponseSummaryTaskGuid_QNAME, String.class, ACNServiceResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", name = "SummaryTaskName", scope = ACNServiceResponse.class)
    public JAXBElement<String> createACNServiceResponseSummaryTaskName(String value) {
        return new JAXBElement<String>(_ACNServiceResponseSummaryTaskName_QNAME, String.class, ACNServiceResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/ACN_MSPS_RTC", name = "WorkPlanUrl", scope = ACNServiceResponse.class)
    public JAXBElement<String> createACNServiceResponseWorkPlanUrl(String value) {
        return new JAXBElement<String>(_ACNServiceResponseWorkPlanUrl_QNAME, String.class, ACNServiceResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACNServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ACNCreateWorkPlanFromTemplateWithWRStateResult", scope = ACNCreateWorkPlanFromTemplateWithWRStateResponse.class)
    public JAXBElement<ACNServiceResponse> createACNCreateWorkPlanFromTemplateWithWRStateResponseACNCreateWorkPlanFromTemplateWithWRStateResult(ACNServiceResponse value) {
        return new JAXBElement<ACNServiceResponse>(_ACNCreateWorkPlanFromTemplateWithWRStateResponseACNCreateWorkPlanFromTemplateWithWRStateResult_QNAME, ACNServiceResponse.class, ACNCreateWorkPlanFromTemplateWithWRStateResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACNServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ACNAddTasksToWorkPlanWithWRStateResult", scope = ACNAddTasksToWorkPlanWithWRStateResponse.class)
    public JAXBElement<ACNServiceResponse> createACNAddTasksToWorkPlanWithWRStateResponseACNAddTasksToWorkPlanWithWRStateResult(ACNServiceResponse value) {
        return new JAXBElement<ACNServiceResponse>(_ACNAddTasksToWorkPlanWithWRStateResponseACNAddTasksToWorkPlanWithWRStateResult_QNAME, ACNServiceResponse.class, ACNAddTasksToWorkPlanWithWRStateResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rtcWorkRequestURL", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanRtcWorkRequestURL(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestURL_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "businessArea", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanBusinessArea(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateBusinessArea_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "workPlanName", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanWorkPlanName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateWorkPlanName_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "summary", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanSummary(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateSummary_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "projectManager", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanProjectManager(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateProjectManager_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "estimatedStartDate", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanEstimatedStartDate(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateEstimatedStartDate_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "estimatedFinishDate", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanEstimatedFinishDate(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateEstimatedFinishDate_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "clientName", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanClientName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateClientName_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rtcWorkRequestID", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanRtcWorkRequestID(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestID_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "assignedTo", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanAssignedTo(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateAssignedTo_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "applicationName", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanApplicationName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateApplicationName_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "PSInstanceURL", scope = ACNAddTasksToWorkPlan.class)
    public JAXBElement<String> createACNAddTasksToWorkPlanPSInstanceURL(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStatePSInstanceURL_QNAME, String.class, ACNAddTasksToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "businessArea", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanBusinessArea(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateBusinessArea_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "requestID", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanRequestID(String value) {
        return new JAXBElement<String>(_ACNAddWBSToWorkPlanRequestID_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "requestURL", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanRequestURL(String value) {
        return new JAXBElement<String>(_ACNAddWBSToWorkPlanRequestURL_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "templateName", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanTemplateName(String value) {
        return new JAXBElement<String>(_ACNCreateWorkPlanFromTemplateWithWRStateTemplateName_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "applicationName", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanApplicationName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateApplicationName_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "PSInstanceURL", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanPSInstanceURL(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStatePSInstanceURL_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "workPlanName", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanWorkPlanName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateWorkPlanName_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "summary", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanSummary(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateSummary_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "projectManager", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanProjectManager(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateProjectManager_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "requestRelease", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanRequestRelease(String value) {
        return new JAXBElement<String>(_ACNAddWBSToWorkPlanRequestRelease_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "estimatedStartDate", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanEstimatedStartDate(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateEstimatedStartDate_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "estimatedFinishDate", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanEstimatedFinishDate(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateEstimatedFinishDate_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "clientName", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanClientName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateClientName_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "priority", scope = ACNAddWBSToWorkPlan.class)
    public JAXBElement<String> createACNAddWBSToWorkPlanPriority(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStatePriority_QNAME, String.class, ACNAddWBSToWorkPlan.class, value);
    }

    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rtcWorkRequestURL", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateRtcWorkRequestURL(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestURL_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "businessArea", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateBusinessArea(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateBusinessArea_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "summary", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateSummary(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateSummary_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "projectManager", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateProjectManager(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateProjectManager_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "estimatedStartDate", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateEstimatedStartDate(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateEstimatedStartDate_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "estimatedFinishDate", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateEstimatedFinishDate(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateEstimatedFinishDate_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "templateName", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateTemplateName(String value) {
        return new JAXBElement<String>(_ACNCreateWorkPlanFromTemplateWithWRStateTemplateName_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "clientName", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateClientName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateClientName_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rtcWorkRequestID", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateRtcWorkRequestID(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateRtcWorkRequestID_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "psInstanceURL", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplatePsInstanceURL(String value) {
        return new JAXBElement<String>(_ACNCreateWorkPlanFromTemplateWithWRStatePsInstanceURL_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "applicationName", scope = ACNCreateWorkPlanFromTemplate.class)
    public JAXBElement<String> createACNCreateWorkPlanFromTemplateApplicationName(String value) {
        return new JAXBElement<String>(_ACNAddTasksToWorkPlanWithWRStateApplicationName_QNAME, String.class, ACNCreateWorkPlanFromTemplate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACNServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ACNCreateWorkPlanFromTemplateResult", scope = ACNCreateWorkPlanFromTemplateResponse.class)
    public JAXBElement<ACNServiceResponse> createACNCreateWorkPlanFromTemplateResponseACNCreateWorkPlanFromTemplateResult(ACNServiceResponse value) {
        return new JAXBElement<ACNServiceResponse>(_ACNCreateWorkPlanFromTemplateResponseACNCreateWorkPlanFromTemplateResult_QNAME, ACNServiceResponse.class, ACNCreateWorkPlanFromTemplateResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ACNServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ACNAddWBSToWorkPlanResult", scope = ACNAddWBSToWorkPlanResponse.class)
    public JAXBElement<ACNServiceResponse> createACNAddWBSToWorkPlanResponseACNAddWBSToWorkPlanResult(ACNServiceResponse value) {
        return new JAXBElement<ACNServiceResponse>(_ACNAddWBSToWorkPlanResponseACNAddWBSToWorkPlanResult_QNAME, ACNServiceResponse.class, ACNAddWBSToWorkPlanResponse.class, value);
    }

}
