/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bruce.a.neiman' at '1/25/16 2:06 PM' with Gradle 2.9
 *
 * @author bruce.a.neiman, @date 1/25/16 2:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
